#端口配置
server:
    port: 8088
#jdbc配置
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
#mybatis配置
mybatis:
    #实体类所在包名
    type-aliases-package: com.seenow.pojo
#通用mapper配置
mapper:
    #公用接口类路径
    mappers: com.seenow.dao
    identity: MYSQL